name: Deploy Theme to EasyWP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/sftp-deploy-action@v1.2.4
        with:
          server: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './wp-content/themes/farset-theme-main'
          remote_path: '/wptbox/wp-content/themes/farset-theme-main'
          sftp_only: true
