name: Deploy Theme to EasyWP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/sftp-deploy-action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          sftp_only: true
          local_path: './wp-content/themes/farset-theme-main'
          remote_path: '/wptbox/wp-content/themes/farset-theme-main'
